version: '3.8'

networks:
  noda_network:

services:
  backend:
    container_name: noda_backend
    image: golang:1.22.5-alpine3.20
    volumes:
      - type: bind
        source: .
        target: /src
    command: sh -c "cd /src && go mod download && sleep infinity"
    ports:
      - "7890:5792"
    networks:
      - noda_network
    environment:
      - SERVER_PORT=5792
      - DB_NAME=master
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_HOST=noda_database
      - DB_PASSWORD=secret
      - JWT_SECRET='AJW[;>qs)-gkpQfM@};K7jRS?d)T)3vx$3[]aUp>3$%+3rE;w@X{,2@/[(XT8^G*])

  database:
    container_name: noda_database
    image: postgres:16rc1-alpine3.18
    restart: unless-stopped
    networks:
      - noda_network
    ports:
      - "7891:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/src
    environment:
      - POSTGRES_PASSWORD=secret
      - PROJECT_DIR=/src
