version: '3.8'

networks:
  noda_network:

services:
  backend:
    container_name: noda_backend
    image: golang:1.22.5-alpine3.20
    volumes:
      - type: bind
        source: .
        target: /src
    command: >
      sh -c "
      cd /src &&
      echo 'Installing Go dependencies...' &&
      go mod download &&
      echo 'Go dependencies installed.' &&
      sleep infinity
      "
    ports:
      - "7890:7890"
    networks:
      - noda_network
    environment:
      - SERVER_PORT=7890
      - PG_NAME=master
      - PG_USER=worker
      - PG_PORT=5432
      - PG_HOST=noda_database
      - PG_PASSWORD=secret
      - JWT_SECRET='AJW[;>qs)-gkpQfM@};K7jRS?d)T)3vx$3[]aUp>3$%+3rE;w@X{,2@/[(XT8^G*])

  database:
    container_name: noda_database
    image: postgres:16rc1-alpine3.18
    restart: unless-stopped
    networks:
      - noda_network
    ports:
      - "7891:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/src
    environment:
      - POSTGRES_PASSWORD=secret
      - PROJECT_DIR=/src
